### ISSUE TITLE
Unable to use string validation methods on nullable string attributes

### ISSUE THREAD

**Issue by ClevertonZarelli** [Flutterando/lucid_validation#2]
I encountered a problem when attempting to use the Lucid Validator with a nullable String attribute in my Dart entity. Specifically, when trying to validate a CPF using the validCPF method, it works fine for non-nullable String attributes. However, for a nullable String attribute, I cannot access the validCPF method, even when I use .when to ensure the attribute is not null.

Example with a non-nullable string:
ruleFor((e) => e.cpfRecebedor, key: 'cpf_recebedor') 
    .validCPF(message: 'CPF inválido', code: '1');
    
 This works perfectly.
 
 But for a nullable string:
 
 ruleFor((e) => e.cpfRecebedor, key: 'cpf_recebedor')
    .when((e) => e.cpfRecebedor != null)
    .must((value) => (value ?? '') != '', 'Cpf Invalido', '4');
    
   In the .must method, value is the string representation of cpfRecebedor, but I cannot chain .validCPF or other string-specific validation methods, even after checking for null. This limitation forces me to manually implement logic to validate the CPF instead of leveraging the package's built-in methods.
   
  **Expected Behavior**
I expect to be able to use string-specific validation methods like .validCPF even for nullable attributes, provided that I use a .when clause or handle nullability elsewhere in the rule.

**Steps to Reproduce**
Define a nullable String attribute in the entity, e.g., String? cpfRecebedor.
Attempt to use ruleFor with .validCPF on the nullable string.
Observe that the .validCPF method is unavailable or does not work as expected.
Workaround
Currently, I must validate the nullable String manually using .must, but this defeats the purpose of having built-in validation methods.

Additional Information
Package version: 1.1.0

**Comment by wellgenio** [comment]
Thanks for your report @ClevertonZarelli ! Lucid Validation does not currently support nullable types, but we are working on it.

One fix: using .when does not guarantee that the type is not nullable, it just does not perform the rest of the validations. We are working on a way to guarantee that the type is not nullable.

**Comment by ClevertonZarelli** [comment]
> Thanks for your report @ClevertonZarelli ! Lucid Validation does not currently support nullable types, but we are working on it.
> 
> One fix: using .when does not guarantee that the type is not nullable, it just does not perform the rest of the validations. We are working on a way to guarantee that the type is not nullable.

Thanks atm.
